spring.application.name=sistema-rotas

jwt.security.token.secret=${JWT_SECRET}

spring.datasource.url=jdbc:postgresql://${DB_HOST}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

minio.url=${MINIO_URL}
minio.access-key=${ACCESS_KEY}
minio.secret-key=${SECRET_KEY}